development:
  adapter: postgresql
  database: coding_notes_development

test:
  adapter: postgresql
  database: coding_notes_test

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>
